#spring:
#  datasource:
#    url: "jdbc:mysql://192.168.74.14:3306/mybatis_example?useUnicode=true&characterEncoding=utf-8&useSSL=false"
#    username: "root"
#    password: "root"
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

#下面的配置是在 groupid=com.github.drtrang artifactId=druid-spring-boot2-starter的第三方jar包中才会使用的
#    druid:
#      username: "root"
#      password: "root"
#      url: "jdbc:mysql://192.168.74.14:3306/mybatis_example?useUnicode=true&characterEncoding=utf-8&useSSL=false"
#      driver-class-name: com.mysql.jdbc.Driver
#                         com.microsoft.sqlserver.jdbc.SQLServerDriver
#
spring:
  ##数据库连接信息
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      my-db-type: mysql
      my-db-name: 'my-test-db-192.168.74.16-3306-mybatis_example'
      jdbc-url: 'jdbc:mysql://192.168.74.16:3306/mybatis_example?useUnicode=true&characterEncoding=utf-8&useSSL=false'
      jdbc-username: root
      jdbc-password: root
      jdbc-driver-class-name: com.mysql.jdbc.Driver
      ###################以下为druid增加的配置##########################
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 3
      minIdle: 3
      maxActive: 10
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

